#!/bin/bash

case "$BLOCK_BUTTON" in
    1) dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause ;;
    2) dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous ;;
    3) dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next ;;
esac

. "/home/kevin/.cache/wal/colors.sh"
long_title=$(spotify-now -i '%artist - %title' -p '' -e '' | sed 's/&/&amp;/g')
short_title=$(spotify-now -i '%title' -p '' -e '' | sed 's/&/&amp;/g')
printf "$long_title\n$short_title\n%s\n" "$color7"
