#!/bin/bash

base_bg_path="/home/kevin/Pictures/Backgrounds"

brightness_choice=$(echo -e "dim\nbright" | dmenu -i)
editing_choice=$(echo -e "editing\nnon-editing" | dmenu -i)

bg_path="$base_bg_path/$brightness_choice/$editing_choice"
wal_cmd="wal -i $bg_path"
eval "$wal_cmd"
